# Q2 SC19B081

## 1.

Create the following variables as NumPy arrays<br><br>
$A = \left[ \begin{array}{rrrr} -2 & -3 \\ 1 & 0 \end{array}\right]$,
$B = \left[ \begin{array}{rrrr} 1 & 1 \\ 1 & 0 \end{array}\right]$,
$x = \left[ \begin{array}{rrrr} -1  \\ 1 \end{array}\right]$


In [1]:
import numpy as np  

In [28]:
A = np.array([[-2,-3],[1,0]])
B = np.array([[1,1],[1,0]])
x = np.array([[-1,1]]).T
print(A)
print(B)
print(x)

[[-2 -3]
 [ 1  0]]
[[1 1]
 [1 0]]
[[-1]
 [ 1]]


## 2.

Compute $C = A^{-1}$

In [4]:
C = np.linalg.inv(A)
print(C)

[[-2.77555756e-17  1.00000000e+00]
 [-3.33333333e-01 -6.66666667e-01]]


## 3.

Confirm that $A · C = I$ and $C · A = I$,  where $I$ is a 2 x 2 identity matrix.

In [5]:
print(A@C)
print(C@A)

[[ 1.00000000e+00 -1.11022302e-16]
 [-2.77555756e-17  1.00000000e+00]]
[[1.00000000e+00 8.32667268e-17]
 [0.00000000e+00 1.00000000e+00]]


## 4.

 Compute $Ax$

In [29]:
print(A@x)

[[-1]
 [-1]]


## 5.

Compute $A^{T}A$

In [7]:
print(A.T@A)

[[5 6]
 [6 9]]


## 6.

Compute $(AB)^{T}$

In [8]:
print((A@B).T)

[[-5  1]
 [-2  1]]


## 7.

Compute $Ax - Bx$ 

In [30]:
print(A@x - B@x)

[[-1]
 [ 0]]


## 8.

Compute $||x||$

In [10]:
print(np.linalg.norm(x))

1.4142135623730951


## 9.

Compute $||Ax - Bx||$ 

In [11]:
print(np.linalg.norm(A@x - B@x))

1.0


## 10. 

Print the first column of $A$ (do NOT use a loop—use array “slicing” instead)

In [16]:
print(A[:,0])

[-2  1]


## 11.

Assign the vector $x$ to the first column of $B$ and call this new variable D. Do NOT use a loop—use
“array slicing” instead.

In [38]:
D = np.array([[0,0],[0,0]])
D[0,:] = x.T
D[1,:] = B[:,1].T
D = D.T
print(D)

[[-1  1]
 [ 1  0]]
[[1 1]
 [1 0]]


## 12.

Compute the element-wise product between the first column of $A$ and the second column of $A$

In [42]:
print(np.multiply(A[:,0],A[:,1]))

[6 0]
